[package]
name = "web3rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
env_logger = "0.11.3"
time = "0.3.44"
web3 = "0.19.0"
hex-literal = "1.1.0"
hex = "0.4.3"
secp256k1 = "0.31.1"
dotenv = "0.15.0"
idna = "1.1.0"
